-- 년, 월, 성별 별 상품을 구매한 회원수를 집계
-- YEAR	MONTH	GENDER	USERS 조회
-- YEAR	MONTH	GENDER 기준 오름차순
-- 조건1. 성별 정보가 없을 경우 결과에서 제외
-- SELECT * FROM USER_INFO
-- SELECT * FROM ONLINE_SALE 
-- ORDER BY SALES_DATE

SELECT TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH, GENDER
, COUNT(DISTINCT S.USER_ID) AS USERS
FROM USER_INFO I JOIN ONLINE_SALE S
ON I.USER_ID = S.USER_ID
GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')), GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER