-- 음식종류별 즐겨찾기수 가장 많은 식당
-- 음식종류, ID, 식당이름, 즐겨찾기수 조회 (음식기준 내림차순)
-- 음식종류 별로 

-- SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_INFO
-- ORDER BY FOOD_TYPE 


SELECT A.FOOD_TYPE, B.REST_ID, B.REST_NAME, A.FAVORITES FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO
    GROUP BY FOOD_TYPE
) A JOIN REST_INFO B
ON A.FAVORITES = B.FAVORITES AND A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY FOOD_TYPE DESC

-- SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO
-- GROUP BY FOOD_TYP
