-- 조건 1. 들어올땐 중성화X 나갈땐 중성화O
-- 아이디, 생물 종, 이름 조회 (아이디 순으로 조회)
-- SELECT * FROM ANIMAL_INS
-- SELECT * FROM ANIMAL_OUTS


SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE (I.SEX_UPON_INTAKE NOT LIKE 'Spayed%' AND I.SEX_UPON_INTAKE NOT LIKE 'Neutered%')
AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')