-- 조건 1. 2022년 10월 5일에 등록
-- BOARD_ID	WRITER_ID	TITLE	PRICE	STATUS 조회
-- 거래상태가 SALE이면 판매중, RESERVED면 예약중, DONE이면 거래완료로 분류하여 출력
-- BOARD_ID	기준 내림차순
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE
, CASE
    WHEN STATUS = 'SALE' THEN '판매중'
    WHEN STATUS = 'RESERVED' THEN '예약중'
    WHEN STATUS = 'DONE' THEN '거래완료'
END AS STATUS
FROM USED_GOODS_BOARD
WHERE TO_CHAR(CREATED_DATE, 'YYYY-MM-DD') = '2022-10-05'
ORDER BY BOARD_ID DESC