-- 조건 1. 2022년 10월 5일
-- BOARD_ID	WRITER_ID	TITLE	PRICE	STATUS 조회
-- 조건 2. SALE이면 판매중, RESERVED면 예약중, DONE 이면 거래완료로 분류하여 출력
-- BOARD_ID기준 내림차순

-- SELECT * FROM USED_GOODS_BOARD

SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, CASE
    WHEN STATUS = 'DONE' THEN '거래완료'
    WHEN STATUS = 'RESERVED' THEN '예약중'
    WHEN STATUS = 'SALE' THEN '판매중'
END AS STATUS
FROM USED_GOODS_BOARD
WHERE TO_CHAR(CREATED_DATE, 'YYYY-MM-DD') = '2022-10-05'
ORDER BY BOARD_ID DESC