-- 가격이 제일 비싼 식품
-- PRODUCT_ID	PRODUCT_NAME	PRODUCT_CD	CATEGORY	PRICE 조회

-- SELECT * FROM FOOD_PRODUCT

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (
    SELECT MAX(PRICE) FROM FOOD_PRODUCT
)