-- 조건 1. 게시물 3건 이상 등록한 사용자
-- USER_ID, NICKNAME, 전체주소, 전화번호 조회 (전화번호 경우 000-0000-0000 형태로 삽입하여 출력)
-- USER_ID 기준 내림차순

-- SELECT * FROM USED_GOODS_BOARD
-- SELECT * FROM USED_GOODS_USER

SELECT U.USER_ID, U.NICKNAME, U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2 AS 전체주소
-- SELECT U.USER_ID, U.NICKNAME, CONCAT(CONCAT(U.CITY, ' '), U.STREET_ADDRESS1) AS 전체주소
, SUBSTR(U.TLNO, 1, 3) || '-' || SUBSTR(U.TLNO, 4, 4) || '-' || SUBSTR(U.TLNO, 8, 4) AS 전화번호
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID, U.NICKNAME, U.TLNO, U.CITY, U.STREET_ADDRESS1, U.STREET_ADDRESS2
HAVING COUNT(U.USER_ID) >= 3
ORDER BY USER_ID DESC