-- 조건 1. 평균 대여 기간이 7일 이상인 자동차들
-- CAR_ID	AVERAGE_DURATION 조회
-- 평균 대여 기간은 소수점 두번째 자리에서 반올림
-- 평균 대여 기간을 기준으로 내림차순 정렬, 자동차 ID를 기준으로 내림차순 정렬

SELECT CAR_ID, ROUND(AVG(END_DATE - START_DATE+1), 1) AS AVERAGE_DURATION 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(END_DATE - START_DATE+1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

-- SELECT CAR_ID, TO_CHAR(ROUND(AVG(TO_NUMBER(END_DATE - START_DATE)), 1), 'FM999.0') AS AVERAGE_DURATION
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE (TO_NUMBER(END_DATE - START_DATE)) >= 7
-- GROUP BY CAR_ID
-- ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
