-- ANIMAL_OUTS 의 DATETIME이 입양일
-- 조건 1. 입양 못 간 동물 중, 가장 오래 남은 TOP3 이름과 보호 시작일 조회 I.NAME, I.DATETIME(I.DATETIME 기준)

-- SELECT * FROM ANIMAL_INS
-- SELECT * FROM ANIMAL_OUTS

SELECT B.NAME, B.DATETIME
FROM (
    SELECT ROWNUM AS RNUM, A.*
    FROM (
        SELECT I.NAME, I.DATETIME
        FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
        WHERE O.ANIMAL_ID IS NULL
        ORDER BY I.DATETIME
    ) A
) B
WHERE B.RNUM BETWEEN 1 AND 3
-- ALIAS 명칭으로 ROWNUM을 변경 안하면 B.ROWNUM이 아니라 ROWNUM으로 써도 됨