-- USED_GOODS_BOARD와 USED_GOODS_USER
-- 조건 1.완료된 중고 거래의 총금액이 70만 원 이상
-- STATUS = DONE AND PRICE
-- B.WRITER_ID = U.USER_ID
-- USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES (총 거래 금액) 금액 기준 오름차순 


SELECT U.USER_ID, U.NICKNAME, B.TOTAL_SALES FROM (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) B JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
WHERE B.TOTAL_SALES >= 700000
ORDER BY B.TOTAL_SALES ASC


