-- ANIMAL_TYPE	NAME	SEX_UPON_INTAKE 조회
-- 아이디 순으로 조회
-- 조건 1. 이름이 없는 동물의 이름은 "No name"

-- SELECT * FROM ANIMAL_INS

SELECT ANIMAL_TYPE, NVL(NAME, 'No name') AS NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID