-- 만원 단위의 가격대 별
-- 상품 개수를 출력(PRICE_GROUP, PRODUCTS)
-- select 조건 10,000원 이상 ~ 20,000 미만인 구간인 경우 10,000
-- 가격대를 기준으로 오름차순

-- SELECT * FROM PRODUCT

SELECT TRUNC(PRICE, -4) AS PRICE_GROUP, COUNT(TRUNC(PRICE, -4)) AS PRODUCTS
FROM PRODUCT
GROUP BY TRUNC(PRICE, -4)
ORDER BY PRICE_GROUP