-- 카테고리 별 도서 판매량 합산
-- 조건 1. 2022년 1월
-- 카테고리, 총 판매량
-- 카테고리명 기준 오름차순

-- BOOK B JOIN BOOK_SALES BS
-- 선 조인 후 그룹핑

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES FROM (
    SELECT * FROM BOOK B JOIN BOOK_SALES BS
    ON B.BOOK_ID = BS.BOOK_ID
    WHERE SUBSTR(TO_CHAR(BS.SALES_DATE, 'YYYY-MM-DD'), 1, 7) = '2022-01'
)
GROUP BY CATEGORY
ORDER BY CATEGORY

-- SELECT * FROM BOOK B JOIN BOOK_SALES BS
-- ON B.BOOK_ID = BS.BOOK_ID
-- WHERE SUBSTR(TO_CHAR(BS.SALES_DATE, 'YYYY-MM-DD'), 1, 7) = '2022-01'

-- SELECT * FROM BOOK
-- SELECT * FROM BOOK_SALES



