-- 상품코드 별
-- 매출액(판매가 * 판매량) 합계
-- 매출액을 기준으로 내림차순 정렬, 상품코드를 기준으로 오름차순

-- SELECT * FROM PRODUCT
-- SELECT * FROM OFFLINE_SALE


SELECT P.PRODUCT_CODE, (P.PRICE * SUM(O.SALES_AMOUNT)) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE, P.PRICE
ORDER BY SALES DESC, PRODUCT_CODE