-- 조건 1. 2022년 10월 16일에 대여 여부에 따라 대여중, 대여 가능 AVAILABILITY로 표시
-- CAR_ID, AVAILABILITY 조회
-- CAR_ID 기준 내림차순 정렬
-- SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- 중복 데이터 처리 하는 방법을 고민해야 됨
-- 1). 차 아이디별 가장 높은 END_DATE 값들만 가져옴 (이 때 서브쿼리로 가져와서 JOIN을 해야 하는가?)


-- SELECT CAR_ID
-- , TO_CHAR(START_DATE, 'YYYY-MM-DD') AS STARTD, TO_CHAR(END_DATE, 'YYYY-MM-DD') AS ENDD
-- , CASE
--     WHEN TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-10-16'
--     AND TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-10-16' THEN '대여중'
--     ELSE '대여 가능'
-- END AS AVAILABILITY
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- ORDER BY CAR_ID DESC, TO_CHAR(END_DATE, 'YYYY-MM-DD') DESC

SELECT DISTINCT CAR_ID
, CASE
    WHEN CAR_ID IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE '2022-10-16' BETWEEN TO_CHAR(START_DATE, 'YYYY-MM-DD') 
        AND TO_CHAR(END_DATE, 'YYYY-MM-DD')
    ) THEN '대여중'
    ELSE '대여 가능'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC




-- SELECT DISTINCT B.CAR_ID
-- , TO_CHAR(B.START_DATE, 'YYYY-MM-DD') AS STARTD, TO_CHAR(B.END_DATE, 'YYYY-MM-DD') AS ENDD
-- , CASE
--     WHEN TO_CHAR(B.START_DATE, 'YYYY-MM-DD') <= '2022-10-16'
--     AND TO_CHAR(B.END_DATE, 'YYYY-MM-DD') >= '2022-10-16' THEN '대여중'
--     ELSE '대여 가능'
-- END AS AVAILABILITY
-- FROM (
--     SELECT CAR_ID, MAX(END_DATE) AS END_DATE
--     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--     GROUP BY CAR_ID
-- ) A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
-- ON A.END_DATE = B.END_DATE
-- ORDER BY B.CAR_ID DESC


