-- ANIMAL_ID	NAME	중성화 조회
-- ANIMAL_ID 순으로 조회
-- 중성화가 되어있다면 'O', 아니면'X'

-- SELECT * FROM ANIMAL_INS
-- ORDER BY ANIMAL_ID

SELECT ANIMAL_ID, NAME, CASE
 WHEN SEX_UPON_INTAKE LIKE 'Neutered%' or SEX_UPON_INTAKE LIKE 'Spayed%' THEN 'O'
 ELSE 'X'
END AS "중성화"
FROM ANIMAL_INS
ORDER BY ANIMAL_ID