-- OUT_DATE 5월 1일을 기준, 5월 1일 이하 출고 완료 이후 대기 없으면 미정
-- 주문 ID, 제품 ID, 출고일자, 출고여부를 조회 (주문 ID를 기준으로 오름차순)
-- SELECT * FROM FOOD_ORDER

SELECT ORDER_ID, PRODUCT_ID, TO_CHAR(OUT_DATE, 'YYYY-MM-DD') AS OUT_DATE,
CASE 
    WHEN TO_CHAR(OUT_DATE, 'YYYYMMDD') > '20220501' THEN '출고대기'
    WHEN TO_CHAR(OUT_DATE, 'YYYYMMDD') <= '20220501' THEN '출고완료'
    WHEN TO_CHAR(OUT_DATE, 'YYYYMMDD') IS NULL THEN '출고미정'
END AS 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID
