-- 조건 1. 생산일자 2022년 5월
-- PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES
-- TOTAL_SALES 기준 내림차순, PRODUCT_ID 기준 오름차순

-- SELECT * FROM FOOD_PRODUCT
-- SELECT * FROM FOOD_ORDER

-- SELECT *
-- FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
-- ON P.PRODUCT_ID = O.PRODUCT_ID

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE
ORDER BY TOTAL_SALES DESC, PRODUCT_ID