-- 조건 1. 09:00부터 19:59까지
-- 각 시간대별로 입양이 몇 건 (시간대 순)
-- SELECT * FROM ANIMAL_OUTS
-- ORDER BY DATETIME

-- SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(DATETIME) AS COUNT
SELECT DECODE(TO_CHAR(DATETIME, 'HH24'), '09', 9, TO_CHAR(DATETIME, 'HH24')) AS HOUR, COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME, 'HH24') >= 9 AND TO_CHAR(DATETIME, 'HH24') < 20
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY TO_CHAR(DATETIME, 'HH24')

-- SELECT DATETIME