-- 조건 1. 09:00부터 19:59까지
-- 각 시간대별로 입양이 몇 건이나 발생했는지 조회
-- 시간대 순으로 정렬

-- SELECT * FROM ANIMAL_OUTS

SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
HAVING TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) BETWEEN 9 AND 19
ORDER BY HOUR