-- 조건 1. '경제' 카테고리
-- BOOK_ID, AUTHOR_NAME, PUBLISHED_DATE
-- PUBLISHED_DATE 기준 asc

-- SELECT * FROM BOOK
-- SELECT * FROM AUTHOR

SELECT B.BOOK_ID, A.AUTHOR_NAME, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK B JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE