-- 조건1. 통풍시트 OR 열선시트 OR 가죽시트 가 OPTIONS에 있어야 한다
-- 자동차 종류별 COUNT(*) AS CARS
-- 자동차 종류 기준 오름차순

SELECT CAR_TYPE, COUNT(*) AS CARS FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE