-- 조건 1. 생일이 3월
-- 조건 2. 여성
-- MEMBER_ID	MEMBER_NAME	  GENDER	DATE_OF_BIRTH 조회
-- 조건 3. 전화번호가 NULL인 경우는 출력대상에서 제외
-- 회원ID를 기준으로 오름차순 정렬

-- SELECT * FROM MEMBER_PROFILE

SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TO_CHAR(DATE_OF_BIRTH, 'MM') = 03 AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID